name: Create Release

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: 'major | minor | patch'
        required: true
        default: patch
      description:
        description: Changes in this Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump versions
        run: yarn version --${{ github.event.inputs.versionIncrement }} --no-git-tag-version
      
      - name: Read new version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Create release
          branch: master
          commit_options: '--no-verify --signoff'
          file_pattern: './package.json'
          tagging_message: 'v${{ steps.package-version.outputs.version }}'
          push_options: '--force'
          skip_dirty_check: true
          skip_fetch: true
      
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ steps.package-version.outputs.version }}'
          release_name: v${{ steps.package-version.outputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
